database:
  driverClass: org.postgresql.Driver
  user: tester
  password: thisisatest
  url: jdbc:postgresql://localhost:5432/test
server:
  type: default
  maxThreads: 128
  minThreads: 4
logging:
  level: WARN
  loggers:
    com.intellias: DEBUG
